#! /bin/bash

set -e
if [ -z $ENV ]; then ENV=$APP_ENVIRONMENT; fi

SECRETS_FILE="config/environments/${ENV}/secrets.enc.yaml"

PROPERTIES_FILE="config/environments/${ENV}/${ENV}.properties"

source ${PROPERTIES_FILE}
source helper
source azure/az_lib

check_az_cli

logger "INFO" "Authenticating to Azure"
az_login

logger "INFO" "Reading secrets from local encrypted file"
fetch_secrets $SECRETS_FILE

