# Infrastructure configs
ENV="dev"
LOCATION="eastus"
RESOURCE_GROUP="rg-${ENV}"
VNET_NAME="vnet-${ENV}"
ENABLE_SUBNET_CREATION="true"
WEBSERVICE_SUBNET_NAME="webservice-subnet-${ENV}"
WEBSERVICE_SUBNET_PREFIX="10.1.0.0/24"
WEBSERVICE_RUNTIME_SUBNET_NAME="webservice-runtime-subnet-${ENV}"
WEBSERVICE_RUNTIME_SUBNET_PREFIX="10.1.1.0/24"
UI_SUBNET_NAME="ui-subnet-${ENV}"
UI_SUBNET_PREFIX="10.1.0.0/24"
KEY_VAULT_NAME="kv-${ENV}"
ENABLE_APP_INSIGHTS="false"
APP_INSIGHTS_NAME="app-insights-${ENV}"
APP_INSIGHTS_SAMPLING_RATE=30

#------------------------------
# Webapp configs

SPRING_APPS_SERVICE="spring-apps-${ENV}"
APP_SERVICE_PLAN="app_service_${ENV}"
SKU="B1"
WEBAPP_NAME="webservice_${ENV}"
JAVA_VERSION="11"
RUNTIME="JAVA|11-java11"
NODE_VERSION="14.0"

#----------------------------------
# Artifact configs

ARTIFACT_FEED_NAME="ArtifactFeed_${ENV}"
ARTIFACT_PACKAGE_NAME="AppPackage_${ENV}"
ARTIFACT_VERSION="1.0.0"
ARTIFACT_URL="https://pkgs.${ENV}.azure.com/${ORG_NAME}/${PROJECT_NAME}/_artifacts/feed/${ARTIFACT_FEED_NAME}"

