#! /bin/bash

# Set error handling to exit the script immediately if a command fails
set -e

# Function to deploy spring-boot artifacts
deploy_webservice_artifacts() {
    # Deploy the Spring Boot application artifact
    logger "INFO" "Deploying Spring Boot application artifact to app: $SPRING_APP_NAME"

    # Deploy the artifact to Azure Spring Apps
    deploy_artifact="az spring app deploy --name $SPRING_APP_NAME --service $SPRING_APPS_SERVICE --resource-group $RESOURCE_GROUP \
                    --artifact-path $LOCAL_ARTIFACT_DIR/$SPRING_APP_PACKAGE_NAME --deployment-name $SPRING_APP_DEPLOYMENT_NAME \
                    --disable-probe $SPRING_APP_DISABLE_PROBE --grace-period $SPRING_APP_GRACE_PERIOD --jvm-options=$SPRING_APP_JAVA_OPTIONS' \
                    --language-framework "springboot" --runtime-version $SPRING_APP_RUNTIME_VERSION --version $APP_VERSION"

    eval "$deploy_artifact"

    if [ $? -ne 0 ]; then
        logger "ERROR" "Failed to deploy artifact to Spring Boot app: $SPRING_APP_NAME"
        exit 1
    fi

    logger "INFO" "Artifact deployed successfully to Spring Boot app: $SPRING_APP_NAME"

}

# Function to update new version of webservice artifacts
update_webservice_artifacts() {
    local artifact="$1"

    # Update the Spring Boot application artifact
    logger "INFO" "Updating Spring Boot application version ${APP_VERSION} artifact to app: $SPRING_APP_NAME"

    # Update the artifact to Azure Spring Apps
    update_artifact="az spring app deploy --name $SPRING_APP_NAME --service $SPRING_APPS_SERVICE --resource-group $RESOURCE_GROUP \
                    --artifact-path "$artifact" --deployment-name $SPRING_APP_DEPLOYMENT_NAME \
                    --runtime-version $SPRING_APP_RUNTIME_VERSION --version $APP_VERSION"

    eval "$update_artifact"

    if [ $? -ne 0 ]; then
        logger "ERROR" "Failed to update artifact to Spring Boot app: $SPRING_APP_NAME"
        exit 1
    fi

    logger "INFO" "Artifact ["$artifact"] updated successfully to Spring Boot app: $SPRING_APP_NAME"

}

