#! /bin/bash

# Set error handling to exit the script immediately if a command fails
set -e

# Function to deploy spring-boot artifacts
deploy_webservice_artifacts() {
    # Deploy the Spring Boot application artifact
    logger "INFO" "Deploying Spring Boot application artifact to app: $SPRING_APP_NAME"

    # Deploy the artifact to Azure Spring Apps
    deploy_artifact="az spring app deploy --name $SPRING_APP_NAME --service $SPRING_APPS_SERVICE --resource-group $RESOURCE_GROUP \
                    --artifact-path $LOCAL_ARTIFACT_DIR/$SPRING_APP_PACKAGE_NAME --deployment-name $SPRING_APP_DEPLOYMENT_NAME \
                    --disable-probe $SPRING_APP_DISABLE_PROBE --grace-period $SPRING_APP_GRACE_PERIOD --jvm-options=$SPRING_APP_JAVA_OPTIONS' \
                    --language-framework "springboot" --runtime-version $SPRING_APP_RUNTIME_VERSION --version $APP_VERSION"

    eval "$deploy_artifact"

    if [ $? -ne 0 ]; then
        logger "ERROR" "Failed to deploy artifact to Spring Boot app: $SPRING_APP_NAME"
        exit 1
    fi

    logger "INFO" "Artifact deployed successfully to Spring Boot app: $SPRING_APP_NAME"

}

# Function to deploy new spring-boot artifacts
update_webservice_artifacts() {
    # Update the Spring Boot application artifact
    logger "INFO" "Updating Spring Boot application artifact to app: $SPRING_APP_NAME"

    # Update the artifact to Azure Spring Apps
    update_artifact="az spring app deploy --name $SPRING_APP_NAME --service $SPRING_APPS_SERVICE --resource-group $RESOURCE_GROUP \
                    --artifact-path $LOCAL_ARTIFACT_DIR/$SPRING_APP_PACKAGE_NAME --deployment-name $SPRING_APP_DEPLOYMENT_NAME \
                    --runtime-version $SPRING_APP_RUNTIME_VERSION --version $APP_VERSION"

    eval "$update_artifact"

    if [ $? -ne 0 ]; then
        logger "ERROR" "Failed to update artifact to Spring Boot app: $SPRING_APP_NAME"
        exit 1
    fi

    logger "INFO" "Artifact [$LOCAL_ARTIFACT_DIR/$SPRING_APP_PACKAGE_NAME] updated successfully to Spring Boot app: $SPRING_APP_NAME"

}



# Create App Service Plan
logger "DEBUG" "Checking if App Service Plan '$APP_SERVICE_PLAN' exists..."
if ! az appservice plan show --name $APP_SERVICE_PLAN --resource-group $RESOURCE_GROUP > /dev/null 2>&1; then
    logger "INFO" "App Service Plan '$APP_SERVICE_PLAN' does not exist. Creating..."

    az appservice plan create --name $APP_SERVICE_PLAN --resource-group $RESOURCE_GROUP --sku $SKU

    if [ $? -ne 0 ]; then
        logger "ERROR" "Failed to create app service plan"
        exit 1
    fi
else
    logger "DEBUG" "App Service Plan '$APP_SERVICE_PLAN' already exists."
fi

# Create Web App
logger "DEBUG" "Checking if Web App '$WEBAPP_NAME' exists..."
if ! az webapp show --name $WEBAPP_NAME --resource-group $RESOURCE_GROUP > /dev/null 2>&1; then
    logger "INFO" "Web App '$WEBAPP_NAME' does not exist. Creating..."

    az webapp create --resource-group $RESOURCE_GROUP --plan $APP_SERVICE_PLAN --name $WEBAPP_NAME --runtime "JAVA|$JAVA_VERSION-java$JAVA_VERSION" --deployment-local-git

    if [ $? -ne 0 ]; then
        logger "ERROR" "Failed to create web app"
        exit 1
    fi
else
    logger "DEBUG" "Web App '$WEBAPP_NAME' already exists."

fi

# Configure Java Version
logger "INFO" "Configuring Java Version..."
az webapp config set --resource-group $RESOURCE_GROUP --name $WEBAPP_NAME --java-version $JAVA_VERSION
if [ $? -ne 0 ]; then
  logger "ERROR" "Failed to configure Java version"
  exit 1
fi

# Download the artifact from Azure Artifacts
logger "INFO" "Downloading artifact from Azure Artifacts..."
curl -u $DEPLOYMENT_USER:$DEPLOYMENT_PASSWORD \
     -L "$ARTIFACT_URL/$ARTIFACT_PACKAGE_NAME/$ARTIFACT_VERSION/$ARTIFACT_PACKAGE_NAME-$ARTIFACT_VERSION.jar" \
     -o myapp.jar
if [ $? -ne 0 ]; then
    logger "ERROR" "Failed to download artifact from Azure Artifacts"
    exit 1
fi

# Create a temporary deployment package (ZIP file)
logger "INFO" "Creating deployment package..."
TEMP_DEPLOYMENT_DIR="${ENV}_deployment_package"
mkdir -p ${TEMP_DEPLOYMENT_DIR}
cp myapp.jar ${TEMP_DEPLOYMENT_DIR}/
cd ${TEMP_DEPLOYMENT_DIR}
zip -r myapp.zip myapp.jar
cd ..
if [ $? -ne 0 ]; then
    logger "ERROR" "Failed to create deployment package"
    exit 1
fi

# Deploy to Azure App Service
logger "INFO" "Deploying to Azure App Service..."
az webapp deployment source config-zip --resource-group $RESOURCE_GROUP --name $WEBAPP_NAME --src ${TEMP_DEPLOYMENT_DIR}/myapp.zip
if [ $? -ne 0 ]; then
    logger "ERROR" "Failed to deploy application to Azure App Service"
    exit 1
fi

logger "INFO" "Deployment successful!"

# Cleanup
rm -rf ${TEMP_DEPLOYMENT_DIR}
