# Infrastructure configs
ENV="dr"
LOCATION="eastus"
RESOURCE_GROUP="rg-${ENV}"
VNET="vnet-${ENV}"
KEY_VAULT_NAME="kv-${ENV}"

#------------------------------
# Webapp configs

SPRING_APPS_SERVICE="spring-apps-${ENV}"
APP_SERVICE_PLAN="app_service_${ENV}"
SKU="B1"
WEBAPP_NAME="webservice_${ENV}"
JAVA_VERSION="11"
RUNTIME="JAVA|11-java11"
NODE_VERSION="14.0"

#----------------------------------
# Artifact configs

ARTIFACT_FEED_NAME="ArtifactFeed_${ENV}"
ARTIFACT_PACKAGE_NAME="AppPackage_${ENV}"
ARTIFACT_VERSION="1.0.0"
ARTIFACT_URL="https://pkgs.${ENV}.azure.com/${ORG_NAME}/${PROJECT_NAME}/_artifacts/feed/${ARTIFACT_FEED_NAME}"

