ENV=dr
LOCATION=eastus
RESOURCE_GROUP=rg_${ENV}
VNET=vnet_${ENV}
DB2_CONNECTION_STRING=jdbc:db2://dev-db2-server:50000/DEVDB
ORACLE_CONNECTION_STRING=jdbc:oracle:thin:@dev-oracle-server:1521:DEVDB
NODE_VERSION=14.0
JAVA_VERSION=11
