KEYVAULT_NAME: kv-dr
TENANT_ID: 3erewfasr3-3d4d-324rf-43rew-432re432rewr3
APP_HOSTNAME: "dr.webapp"
DEPLOYMENT_USER: "dr_deployment_user"
DEPLOYMENT_PASSWORD: "dr_deployment_password"

DB2_DRIVER_CLASS_NAME: "com.ibm.db2.jcc.DB2Driver"
DB2_HOSTNAME: "10.0.0.1"
DB2_PORT: 50000
DB2_DEFAULT_DB_NAME: "SAMPLE"

ORACLE_DRIVER_CLASS_NAME: "oracle.jdbc.OracleDriver"
ORACLE_HOSTNAME: "10.0.1.1"
ORACLE_PORT: 1521
ORACLE_SERVICE_NAME: "orclpdb1"
ORACLE_USERNAME: "admin"
ORACLE_PASSWORD: "P#a$s0rD"
