#! /bin/bash

set -e

# Function to deploy UI build artifact to Azure Web App
deploy_ui_artifact() {
    local resource_group=$RESOURCE_GROUP
    local webapp_name=$WEBAPP_NAME
    local artifact_path="$LOCAL_ARTIFACT_DIR/$WEBAPP_PACKAGE_NAME"
    local track_status=$WEBAPP_TRACK_STATUS
    local deployment_timeout=$WEBAPP_DEPLOYMENT_TIMEOUT
    local slot_name=$WEBAPP_SLOT

    # Check if all required parameters are provided
    if [[ -z "$webapp_name" || -z "$artifact_path" ]]; then
        logger "ERROR" "Missing required Environment values."
        echo "please check to insure <webapp_name> <artifact_path> are defined"
        return 1
    fi

    # Check if the artifact file exists
    if [[ ! -f "$artifact_path" ]]; then
        logger "ERROR" "Artifact file '$artifact_path' not found."
        return 1
    fi

    # Log the start of the deployment
    logger "INFO" "Starting deployment of artifact '$artifact_path' to Azure Web App '$webapp_name' in resource group '$resource_group'."

    # Deploy the artifact using az CLI
    az webapp deployment source config-zip \
        --resource-group "$resource_group" \
        --name "$webapp_name" \
        --src "$artifact_path" \
        --slot "$slot_name" \
        --track-status "$track_status" \
        --deployment-timeout "$deployment_timeout" \
        --output json > deployment_output.json 2>&1

    # Check if the deployment command was successful
    if [[ $? -ne 0 ]]; then
        logger "ERROR" "Deployment failed. Check the output below for details:"
        cat deployment_output.json
        rm deployment_output.json  # Clean up
        return 1
    fi

    logger "INFO" "Successfully deployed artifact '$artifact_path' to Azure Web App '$webapp_name'."
    
    # Clean up deployment output file
    rm deployment_output.json
    
    return 0
}

# Function to update UI artifacts for an Azure Web App service
update_ui_artifacts() {
    local resource_group=$RESOURCE_GROUP
    local webapp_name=$WEBAPP_NAME
    local artifact_path=$1

    logger "INFO" "Updating UI artifacts for Web App: $webapp_name..."

    # Deploy the new artifact to the Azure Web App
    az webapp deployment source config-zip --resource-group "$resource_group" --name "$webapp_name" \
        --src "$artifact_path"

    if [ $? -ne 0 ]; then
        logger "ERROR" "Failed to update UI artifacts for Web App: $webapp_name"
        return 1
    fi

    logger "INFO" "UI artifacts updated successfully for Web App: $webapp_name."
    return 0
}
